import type { Metadata } from "next";
import "./globals.css";
import Menu from "@/components/menu/menu";
import Footer from "@/components/footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
        <Menu/>
        {children}
        <Footer/>
      </body>
      
    </html>
  );
}
